version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./api:/app/api
      - ./data:/app/data
      - ./tests:/app/tests
    depends_on:
      - postgres
      - localstack

  worker:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    env_file: .env
    command: python -m api.jobs.render_report
    volumes:
      - ./api:/app/api
      - ./data:/app/data
    depends_on:
      - postgres
      - localstack

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ephemeris
      POSTGRES_USER: ephem
      POSTGRES_PASSWORD: ephem
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:2.3
    environment:
      SERVICES: s3,sqs
      EDGE_PORT: 4566
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack

volumes:
  pgdata:
  localstack_data:
